name: palette
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.5
  - flask>=3.0.0
  - werkzeug>=3.0.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - scipy>=1.11.0
  - pillow>=10.0.0
  - opencv>=4.8.0
  - pip
  - pip:
    - pytest>=7.4.0
    - pytest-flask>=1.2.0
    - flake8>=6.0.0
    - gunicorn>=21.2.0 